http:
  listener:
    host: "localhost"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  mySQL:
    host: "sql12.freesqldatabase.com"
    port: "3306"
    username: "sql12599830"
    password: "n52bkXy7EL"
    database: "sql12599830"
    